# Generated by Django 3.0.8 on 2020-07-23 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tendencias_musicais_app', '0002_artists'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_artists', models.CharField(max_length=255)),
                ('all_artists_ids', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('duration', models.IntegerField()),
                ('song_name', models.CharField(max_length=126)),
                ('popularity', models.IntegerField()),
                ('source_date', models.DateTimeField()),
                ('main_artist_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tendencias_musicais_app.Artists')),
                ('playlist_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tendencias_musicais_app.Playlists')),
            ],
        ),
    ]
