# Generated by Django 3.0.8 on 2020-07-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendencias_musicais_app', '0003_spotifydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifydata',
            name='position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
