# Generated by Django 3.0.8 on 2020-07-28 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendencias_musicais_app', '0004_spotifydata_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='music_genre_1',
            field=models.CharField(blank=True, max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='artists',
            name='music_genre_2',
            field=models.CharField(blank=True, max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='artists',
            name='music_genre_3',
            field=models.CharField(blank=True, max_length=126, null=True),
        ),
    ]
